name: Test

on:
  workflow_dispatch:
  push:
    paths: [ '**/src/**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
            cache-disabled: false
            cache-read-only: false

      - name: Mark Gradle as Executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew :build
